ALTER TABLE user
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE user
    MODIFY address VARCHAR(255) NULL;

ALTER TABLE user
    MODIFY `description` VARCHAR(255) NULL;

ALTER TABLE user
    MODIFY pfp VARCHAR(255) NULL;

ALTER TABLE user
    MODIFY phone_number VARCHAR(255) NULL;

ALTER TABLE user
    MODIFY status INT NULL;